### PR TITLE
debugview, fixes

### PR DESCRIPTION
**Pull request by DarK-rtfm**

### CODE REVIEW

**Comment by StokiBoti** [comment]
A debugview tökéletesen működik nekem :))

**Comment by RedyAu** [comment]
@DarK-rtfm Add a screenshot to the pr to make it extra cool

**Review by RedyAu — CHANGES_REQUESTED** [review]
Öhm, ez dark módban is fekete?

**Comment by DarK-rtfm** [comment]
> @DarK-rtfm Add a screenshot to the pr to make it extra cool

Ask and you shall receive

**Review by RedyAu — DISMISSED** [review]

**Review by UnknownPlayer78 — APPROVED** [review]

**Pull request merged**
