### PR TITLE
Add material you themed icons

### PR DESCRIPTION
**Pull request by Monke14**
adds Android 12+ themed icons. couldn't test because i don't have access to the filc_premium repo. i'm 99% sure it works though, I tried the same changes on another flutter app with flutter_launcher_icons. you should probably test it before merging

**How it looks:**
Example

### CODE REVIEW

**Comment by 55nknown** [comment]
A filled icon would look better perhaps?

**Comment by Monke14** [comment]
I don't think it looks better, the icon can only have one color

Screenshot_20230301_180716

**Comment by 55nknown** [comment]
I get that, but you should leave an outline around the filled parts.

image

**Comment by Monke14** [comment]
Ok, does this look good?

Screenshot_20230301_182911

**Comment by 55nknown** [comment]
It's more pixelated than my grandma's nokia display, but sure. Maybe a little bit of a thicker outline would do.

**Comment by Monke14** [comment]
Sorry for the images, here are a bit better res ones

Full icon file that I used in the above comment
ic_launcher_monochrome2

Full icon file with a bigger outline
ic_launcher_monochrome3

**Comment by 55nknown** [comment]
Could you please commit the last one please then

**Comment by Monke14** [comment]
I've added the filled in icons. Let me know if you need anything else.

**Pull request merged**
